import React,{useEffect,useState} from "react";
import {Routes,Route,Link,useNavigate,useParams} from "react-router-dom";
import {api} from "./api";

const getUser=()=>JSON.parse(localStorage.getItem("user")||"null");
function Nav(){const nav=useNavigate();const u=getUser();return <nav><Link to="/" className="brand">Eventify</Link><div className="links"><Link to="/">Events</Link>{u&&<Link to="/bookings">My Bookings</Link>}{u?.role==="admin"&&<Link to="/admin">Admin</Link>}{u?<button onClick={()=>{localStorage.clear();nav("/login")}}>Logout</button>:<><Link to="/login">Login</Link><Link to="/register" className="btn">Register</Link></>}</div></nav>}

function Layout({children}){return <><Nav/><main>{children}</main><footer>Eventify • Event Management System</footer></>}
function Events(){const [events,setEvents]=useState([]);const [q,setQ]=useState("");useEffect(()=>{api("/events").then(setEvents).catch(console.error)},[]);return <section><div className="hero"><h1>Discover Amazing Events</h1><p>Book your next experience in a few clicks.</p></div><input className="search" placeholder="Search events..." value={q} onChange={e=>setQ(e.target.value)}/><div className="grid">{events.filter(e=>(e.title+" "+e.location).toLowerCase().includes(q.toLowerCase())).map(e=><article className="card" key={e._id}><div className="poster">{e.title.slice(0,1)}</div><div><h2>{e.title}</h2><p>📅 {new Date(e.date).toLocaleString()}</p><p>📍 {e.location}</p><p>{e.description}</p><strong>₹{e.price}</strong><Link className="btn" to={"/events/"+e._id}>View & Book</Link></div></article>)}</div></section>}

function EventDetails(){const {id}=useParams();const [e,setE]=useState(null);const nav=useNavigate();useEffect(()=>{api("/events/"+id).then(setE).catch(x=>alert(x.message))},[id]);if(!e)return <p>Loading...</p>;return <section className="detail"><div className="poster big">{e.title.slice(0,1)}</div><div><h1>{e.title}</h1><p>{e.description}</p><p>📅 {new Date(e.date).toLocaleString()}</p><p>📍 {e.location}</p><p>Seats left: <b>{e.seatsLeft}</b> / {e.capacity}</p><h2>₹{e.price}</h2><button className="btn" onClick={async()=>{if(!getUser())return nav("/login");try{await api("/bookings",{method:"POST",body:JSON.stringify({eventId:e._id})});alert("Booking confirmed!");nav("/bookings")}catch(x){alert(x.message)}}}>Book Event</button></div></section>}

function Auth({register=false}){const [f,setF]=useState({name:"",email:"",password:""});const nav=useNavigate();return <form className="form" onSubmit={async x=>{x.preventDefault();try{const d=await api(register?"/auth/register":"/auth/login",{method:"POST",body:JSON.stringify(f)});localStorage.setItem("token",d.token);localStorage.setItem("user",JSON.stringify(d.user));nav("/")}catch(e){alert(e.message)}}}><h1>{register?"Create account":"Welcome back"}</h1>{register&&<input placeholder="Full name" required onChange={e=>setF({...f,name:e.target.value})}/>}<input type="email" placeholder="Email" required onChange={e=>setF({...f,email:e.target.value})}/><input type="password" placeholder="Password" minLength="6" required onChange={e=>setF({...f,password:e.target.value})}/><button className="btn">{register?"Register":"Login"}</button></form>}

function Bookings(){const [bs,setBs]=useState([]);const load=()=>api("/bookings/my").then(setBs).catch(e=>alert(e.message));useEffect(load,[]);return <section><h1>My Bookings</h1><div className="list">{bs.map(b=><div className="row" key={b._id}><div><h3>{b.event?.title}</h3><p>{b.event?.location} • {new Date(b.event?.date).toLocaleString()}</p></div><span className={b.status}>{b.status}</span>{b.status==="confirmed"&&<button onClick={async()=>{await api("/bookings/"+b._id+"/cancel",{method:"PATCH"});load()}}>Cancel</button>}</div>)}</div></section>}

function Admin(){const [events,setEvents]=useState([]);const [f,setF]=useState({title:"",description:"",date:"",location:"",capacity:50,price:0});const load=()=>api("/events").then(setEvents);useEffect(load,[]);const save=async e=>{e.preventDefault();try{await api("/events",{method:"POST",body:JSON.stringify(f)});setF({title:"",description:"",date:"",location:"",capacity:50,price:0});load()}catch(x){alert(x.message)}};return <section><h1>Admin Dashboard</h1><form className="adminform" onSubmit={save}>{["title","description","date","location","capacity","price"].map(k=><input key={k} type={k==="date"?"datetime-local":["capacity","price"].includes(k)?"number":"text"} placeholder={k} required={k!=="description"} value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/>)}<button className="btn">Create Event</button></form><h2>Manage Events</h2>{events.map(e=><div className="row" key={e._id}><b>{e.title}</b><span>{new Date(e.date).toLocaleDateString()}</span><button onClick={async()=>{if(confirm("Delete event?")){await api("/events/"+e._id,{method:"DELETE"});load()}}}>Delete</button></div>)}</section>}

export default function App(){return <Layout><Routes><Route path="/" element={<Events/>}/><Route path="/events/:id" element={<EventDetails/>}/><Route path="/login" element={<Auth/>}/><Route path="/register" element={<Auth register/>}/><Route path="/bookings" element={<Bookings/>}/><Route path="/admin" element={<Admin/>}/></Routes></Layout>}